theme: jekyll-theme-primer

site: louino.fr
url: https://louino.fr
title: louino

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

future: true