theme: jekyll-theme-primer

site: nunosint.fr
url: https://nunosint.fr
title: Publications

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

future: true
