theme: jekyll-theme-primer

site: nunosint.github.io
url: https://nunosint.github.io/about/
title: Bienvenue

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

future: true
